### ISSUE TITLE
kernel call from cli

### ISSUE THREAD

**Issue by stek29** [bazad/memctl#2]
I'm not sure if I just missed it, but is there any way to perform kernel_call from cli?

**Comment by bazad** [comment]
Not yet. I'm still considering how best to expose such an interface.

**Comment by stek29** [comment]
The best I can think of is just `kc address args` where args are kword_t's in hex

However, from what I see current arg parsing system doesn't support variadic-like args, so maybe args can be string separated by some other char than space.

**Comment by bazad** [comment]
I've implemented a partial solution in 10ce1775, although it's currently limited to 5 arguments. I'll eventually implement true variadic arguments, at which point you should be able to call arbitrary kernel functions from the CLI.

**Comment by bazad** [comment]
Alright, memctl's CLI now offers better support for kernel call arguments. It doesn't support true repeated/variadic arguments, but it should expose the full power of kernel_call (including stack-based arguments, which must be specified with a width) to the CLI.

**Comment by stek29** [comment]
Awesome!
