### ISSUE TITLE
iPhone 7 iOS 11.3.1 support

### ISSUE THREAD

**Issue by razmashat** [bazad/memctl#8]
Can you add support for iPhone 7 iOS 11.3.1 or at least add tutorial how to add support?

**Comment by bazad** [comment]
Unfortunately I don't have an iPhone 7 running iOS 11.3.1 to test with; can you tell me what is not working?

It appears that the same kernelcache is used for the iPhone 7 and iPhone 8 on 11.3.1, so 9-argument kernel function calling should be supported.

**Comment by bazad** [comment]
Closing this as inactive.
